version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: dwit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - localdb_dwit:/var/lib/postgresql/data

volumes:
  localdb_dwit:
    driver: local
